import type { Metadata } from "next";
import Link from "next/link";
import "../legal.css";

export const metadata: Metadata = { title: "Documentation | Grapho", description: "Start writing, organizing, and exporting with Grapho." };

export default function DocumentationPage() {
  return <main className="legal-page documentation-page"><nav className="legal-nav"><Link href="/app" className="legal-brand"><span>G</span> Grapho</Link><Link href="/app">Open Grapho ↗</Link></nav><article className="legal-content"><p className="legal-kicker">Grapho / Documentation</p><h1>Start with a<br /><i>clear page.</i></h1><p className="legal-lede">A short guide to the writing workspace, document organization, and export flow.</p><section><h2>1. Create a document</h2><p>Open Grapho and choose a project or folder from the sidebar. Create a document, give it a clear title, and start writing directly on the canvas.</p></section><section><h2>2. Shape your writing</h2><p>Use the block menu to add headings, lists, quotes, todos, toggles, callouts, code, tables, dividers, and page breaks. Select text to access inline formatting.</p></section><section><h2>3. Organize simply</h2><p>Use projects and folders to keep related documents together. Documents can be nested, linked, searched, renamed, archived, or restored from trash.</p></section><section><h2>4. Export your work</h2><p>Use the workspace tools to export Markdown, HTML, or plain text. Use Export PDF to open the print flow and save a print-ready document from your browser.</p></section><section><h2>5. Keep your data local</h2><p>Grapho stores browser documents locally in the current workspace. The desktop version uses local native persistence. Use the backup export when you want to move or preserve your workspace.</p></section><section><h2>Keyboard shortcuts</h2><p>Press <strong>/</strong> to open the block menu. Use <strong>Ctrl or Cmd + B</strong> for bold and <strong>Ctrl or Cmd + I</strong> for italic. Open Help &amp; shortcuts inside the workspace for the complete list.</p></section><div className="documentation-links"><Link className="legal-back" href="/app">Open the workspace ↗</Link><Link className="legal-back" href="/privacy">Privacy</Link><Link className="legal-back" href="/terms">Terms</Link></div></article></main>;
}
