import type { Metadata } from "next";
import Link from "next/link";
import "../legal.css";

export const metadata: Metadata = { title: "Privacy | Grapho", description: "How Grapho handles information and documents." };

export default function PrivacyPage() {
  return <main className="legal-page"><nav className="legal-nav"><Link href="/" className="legal-brand"><span>G</span> Grapho</Link><Link href="/app">Open Grapho ↗</Link></nav><article className="legal-content"><p className="legal-kicker">Grapho / Privacy</p><h1>Your writing stays<br /><i>close to you.</i></h1><p className="legal-lede">Grapho is designed as a local-first writing application. This page explains what information the application handles and what it does not.</p><p className="legal-updated">Last updated: 30 August 2026</p><section><h2>1. Documents and local data</h2><p>Documents you create in Grapho are stored locally in your browser or on your computer, depending on the version you use. Grapho does not require an account to write, organize, search, or export documents.</p><p>Because your documents are local, you are responsible for keeping your own backups and protecting access to the device where they are stored.</p></section><section><h2>2. Information we receive</h2><p>The public Grapho website does not ask you to submit personal information. If you contact the project through GitHub, an issue, pull request, or another public project channel, that information is handled by the relevant service and may be publicly visible.</p></section><section><h2>3. Network requests</h2><p>Grapho’s local writing workflow is intended to work without a hosted workspace. Optional external links, downloads, fonts, or repository pages may connect to third-party services when you choose to visit them. Those services have their own privacy policies.</p></section><section><h2>4. Open source</h2><p>Grapho is open source. You can inspect the source code to understand how documents are stored and how the application behaves. The project does not sell your documents or use them for advertising.</p></section><section><h2>5. Changes</h2><p>This policy may change as Grapho develops. The date above identifies the current version. Material changes will be reflected in this page and the public repository.</p></section><section><h2>6. Contact</h2><p>For privacy questions, open an issue in the <a href="https://github.com/Appaxaap/grapho/issues">Grapho repository</a>.</p></section><Link className="legal-back" href="/">← Back to Grapho</Link></article></main>;
}
