import type { Metadata } from "next";
import Link from "next/link";
import { LegalTheme } from "./LegalTheme";
import "./legal.css";

export const metadata: Metadata = { title: "Grapho | Writing workspace", description: "Grapho is a local-first writing application for creating finished documents." };

export default function PublicPage() {
  return <LegalTheme><main className="legal-page"><nav className="legal-nav"><Link href="/app" className="legal-brand"><span>G</span> Grapho</Link><Link href="/app">Open Grapho ↗</Link></nav><article className="legal-content legal-landing"><p className="legal-kicker">Grapho / Public build</p><h1>Write clearly.<br /><i>Finish beautifully.</i></h1><p className="legal-lede">Grapho is a quiet, local-first writing workspace for turning ideas into documents that are ready to share.</p><p className="legal-updated">Version 1.0.0 · Public website in development</p><div className="landing-actions"><Link href="/app" className="landing-primary">Open Grapho ↗</Link><Link href="/documentation">Read documentation</Link></div><section><h2>Writing, without the workspace noise.</h2><p>Start with a blank document, shape it with headings, lists, quotes, tables, callouts, and code, then keep the writing in front of you.</p></section><section><h2>Organize only what matters.</h2><p>Projects, folders, nested documents, search, backlinks, trash, and restore give your work a clear place without turning it into a second job.</p></section><section><h2>Make the document ready to leave.</h2><p>Export Markdown, HTML, plain text, JSON backups, or use the browser print flow for PDF output. Your work stays local and portable.</p></section><section className="landing-status"><h2>The public site is still taking shape.</h2><p>The workspace is available now. The broader public experience will arrive when it has something useful to add.</p><div className="landing-links"><Link href="/documentation">Documentation</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><a href="https://github.com/Appaxaap/grapho" target="_blank" rel="noreferrer">GitHub ↗</a></div></section><Link className="legal-back" href="/app">← Back to Grapho</Link></article></main></LegalTheme>;
}
