"use client";

import Link from "next/link";
import { ArrowUpRight, Check, GitBranch, LockKeyhole } from "lucide-react";
import { Footer } from "../components/site/Footer";
import { Navigation } from "../components/site/Navigation";
import { ProductCanvas } from "../components/site/ProductCanvas";
import "./site.css";

const story = [["01", "Write", "Start with a blank page and keep the thought in front of you."], ["02", "Refine", "Shape hierarchy, rhythm, links, lists, and meaning in context."], ["03", "Deliver", "When it is ready, take the document with you." ]];

export default function PublicSite() {
  return <main className="rebuild-site" id="top"><Navigation />
    <section className="rebuild-hero" aria-labelledby="rebuild-title"><div className="rebuild-hero-orbit" aria-hidden="true"><span>WRITE</span><span>REFINE</span><span>FINISH</span></div><div className="rebuild-hero-copy"><p className="rebuild-kicker">A writing application for finished work</p><h1 id="rebuild-title">Make something<br /><i>worth keeping.</i></h1><p>Grapho gives your words a quiet place to become a document.</p><div className="rebuild-actions"><Link className="rebuild-button" href="/app">Download Grapho <ArrowUpRight size={15} /></Link><a href="https://github.com/Appaxaap/grapho" target="_blank" rel="noreferrer">View source <GitBranch size={13} /></a></div></div><ProductCanvas compact /><span className="rebuild-hero-foot">01 — Begin anywhere <span>Local-first / open source</span></span></section>
    <section className="rebuild-statement" id="product"><p className="rebuild-kicker">The product</p><h2>Writing should not<br />feel like operating <i>software.</i></h2><p className="rebuild-copy">Grapho is deliberately narrow. A beautiful canvas, enough structure to carry an idea, and a clear path to the finished document.</p><ProductCanvas /></section>
    <section className="rebuild-story" id="story"><div className="rebuild-story-heading"><p className="rebuild-kicker">The movement of a thought</p><h2>Write.<br /><i>Shape.</i><br />Send.</h2></div><div className="rebuild-story-list">{story.map(([number, title, copy]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div><div className={`rebuild-story-visual story-${number}`} aria-hidden="true">{title === "Write" && <><b>Start with a clear page</b><i /><i /></>}{title === "Refine" && <><strong>H2</strong><em>I</em><span>↗</span></>}{title === "Deliver" && <><small>READY TO SHARE</small><b>PDF</b></>}</div></article>)}</div></section>
    <section className="rebuild-output"><div><p className="rebuild-kicker">The ending matters</p><h2>Your document<br />deserves a good <i>ending.</i></h2><p className="rebuild-copy">Export work that looks as considered as the writing inside it. Grapho is built around the moment your words leave the editor.</p></div><div className="rebuild-paper"><small>PRODUCT BRIEF · 01</small><h3>A quieter way<br /><i>to write.</i></h3><p>Clear thinking, shaped into a document ready to share.</p><span>READY TO SHARE</span></div></section>
    <section className="rebuild-ownership"><p className="rebuild-kicker">The principle</p><h2>Your work<br /><i>stays yours.</i></h2><p className="rebuild-copy">Local-first storage. Portable documents. Open source. No unnecessary lock-in between you and the work you make.</p><div className="rebuild-principles"><span><LockKeyhole size={14} /> Local by design</span><span><Check size={14} /> No account required</span><span><GitBranch size={14} /> Built in the open</span></div></section>
    <section className="rebuild-open" id="open-source"><div><p className="rebuild-kicker">Open source</p><h2>Readable software<br /><i>for readable work.</i></h2><p className="rebuild-copy">Inspect the source, run it locally, or help shape the next version of Grapho.</p><Link className="rebuild-button rebuild-button-dark" href="https://github.com/Appaxaap/grapho" target="_blank">Explore GitHub <ArrowUpRight size={15} /></Link></div><pre><code><i>const</i> grapho = {`{`}<br />  storage: <b>&quot;local&quot;</b>,<br />  output: <b>&quot;portable&quot;</b>,<br />  source: <b>&quot;open&quot;</b><br />{`}`};</code></pre></section>
    <section className="rebuild-final"><p className="rebuild-kicker">Begin anywhere</p><h2>Make something<br /><i>worth keeping.</i></h2><Link className="rebuild-button rebuild-button-dark" href="/app">Open Grapho <ArrowUpRight size={15} /></Link></section><Footer /></main>;
}
