import type { Metadata } from "next";
import Link from "next/link";
import "../legal.css";

export const metadata: Metadata = { title: "Terms | Grapho", description: "Terms for using the Grapho website and software." };

export default function TermsPage() {
  return <main className="legal-page"><nav className="legal-nav"><Link href="/" className="legal-brand"><span>G</span> Grapho</Link><Link href="/app">Open Grapho ↗</Link></nav><article className="legal-content"><p className="legal-kicker">Grapho / Terms</p><h1>Make things.<br /><i>Keep ownership.</i></h1><p className="legal-lede">These terms describe the basic conditions for using the Grapho website, application, and open-source project.</p><p className="legal-updated">Last updated: 30 August 2026</p><section><h2>1. The project</h2><p>Grapho is an early-stage, open-source writing and document application maintained by Basim Basheer, also known as Appaxaap. The source code is released under the MIT License. The software license is available in the repository’s <a href="https://github.com/Appaxaap/grapho/blob/main/LICENSE">LICENSE</a> file.</p></section><section><h2>2. Acceptable use</h2><p>You may use Grapho for lawful personal, educational, professional, and commercial work. You are responsible for the content you create, import, export, publish, or share using the application.</p></section><section><h2>3. Your documents</h2><p>You retain your rights to documents and content you create. Grapho does not claim ownership of your writing. You are responsible for your local files, backups, exports, and any third-party material you include in a document.</p></section><section><h2>4. Open source and branding</h2><p>The software source is available under the MIT License. The Grapho name, logo, and official project identity are not automatically licensed for use in a way that suggests endorsement or official affiliation. See <a href="https://github.com/Appaxaap/grapho/blob/main/LICENSING.md">LICENSING.md</a> for details.</p></section><section><h2>5. Third-party services</h2><p>Links to GitHub, download providers, fonts, or other external services are provided for convenience. Those services operate under their own terms and policies. Grapho is not responsible for their availability or content.</p></section><section><h2>6. No warranty</h2><p>Grapho is provided “as is” and “as available”, without warranties of any kind. The project is under active development. You should keep backups of important documents and evaluate the software before relying on it for critical work.</p></section><section><h2>7. Changes</h2><p>These terms may be updated as the project develops. The date above identifies the current version. Continued use of Grapho after an update means you accept the revised terms.</p></section><section><h2>8. Contact</h2><p>Questions about these terms can be raised in the <a href="https://github.com/Appaxaap/grapho/issues">Grapho repository issues</a>.</p></section><Link className="legal-back" href="/">← Back to Grapho</Link></article></main>;
}
